set -g prefix C-b 

bind -n C-f resize-pane -Z
bind -n M-] next-window 
bind -n M-[ previous-window 
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D
bind -n M-t split-window -h
bind -n M-h split-window -v

set -g pane-border-style 'fg=#313244'
set -g pane-active-border-style 'fg=#89b4fa'
set -g status-style 'bg=default fg=#cdd6f4'
set -g status-right '#[bg=default,fg=#a6e3a1] '
set -g window-status-current-style 'bg=default fg=#ffffff bold'
set -g window-status-style 'bg=default fg=#ffffff'
