# font_family Monospace Regular
font_size 28 
shell zsh
background_opacity 0.5
background #000000

# BEGIN_KITTY_FONTS
font_family      Noto Sans Mono Regular
bold_font        Noto Sans Mono bold
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#
confirm_os_window_close 0
