
#  _   _                  _                 _  
# | | | |_   _ _ __  _ __| | __ _ _ __   __| | 
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` | 
# |  _  | |_| | |_) | |  | | (_| | | | | (_| | 
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| 
#        |___/|_|                              
#  
# ----------------------------------------------------- 
# Full documentation https://wiki.hyprland.org

source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/cursor.conf
source = ~/.config/hypr/conf/environments.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/layouts.conf
source = ~/.config/hypr/conf/gestures.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/binds.conf
env = VK_DRIVER_FILES,/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
