# You can find more wallpapers in ~/.config/ml4w/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper

wallpaper {
    monitor = DP-4
    path = ~/.config/hypr/wallpapers/bg5.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-6
    path = ~/.config/hypr/wallpapers/bg5.jpg
    fit_mode = cover
}



splash = false
