# Execute your favorite apps at launch
exec-once = waybar
exec-once = hyprpaper
exec-once = dunst
exec-once = systemctl --user start hyprpolkitagent
exec-once = flatpak run com.discordapp.Discord 
exec-once = flatpak run com.adamcake.Bolt
exec-once = flatpak run com.spotify.Client

windowrule = match:class discord, workspace 3
windowrule = match:class Spotify, workspace 3
windowrule = match:title Bolt Launcher, workspace 3
