
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule {
  name = windowrule-1
  workspace = 3
  match:title = (RuneLite - giggseh)
}


windowrule {
  name = windowrule-2
  workspace = special:audio
  float = on
  center = on
  size = 700 500
  match:class = ^(org\.pulseaudio\.pavucontrol)$
}


# htop special workspace
windowrule {
  name = windowrule-3
  workspace = special:audio
  float = on
  center = on
  size = 1000 800
  match:class = ^(htop)$
}

