
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule {
  name = windowrule-2
  workspace = special:audio
  float = false
  center = on
  size = 1000 500
  match:class = ^(org\.pulseaudio\.pavucontrol)$
}


# htop special workspace
windowrule {
  name = windowrule-3
  workspace = special:audio
  float = false
  center = on
  size = 1000 800
  match:class = ^(htop)$
}

